name: Hello world

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs: 
  test:
    name: test-hello
    runs-on: ubuntu-latest
    steps:
      - uses: takinaga-dev/show-results-action@main
        with:
          who-to-greet: 'Mona the Octocat'
          token: ${{ secrets.GITHUBTOKEN }}
    
