name: Hello world

on:
  workflow_dispatch:

jobs: 
　　　　test:
    name: test-hello
    steps:
      - use: takinaga-dev/show-results-action@main
        with:
          who-to-greet: 'Mona the Octocat'
    
